# Generated by Django 5.2.2 on 2025-07-29 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username may contain letters, numbers, spaces, and * @ + - .', regex='^[\\w @*+-]+$')]),
        ),
    ]
